apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-blue
  namespace: enterprise-devops
  labels:
    app: catalog
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
      version: blue
  template:
    metadata:
      labels:
        app: catalog
        version: blue
    spec:
      containers:
        - name: catalog
          image: ghcr.io/avtan88/enterprise/catalog-service:66d79d42987b1e773c8ad7c63dbe6087f433d8a0
          ports:
            - containerPort: 8080
