apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-green
  namespace: enterprise-devops
  labels:
    app: users
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
      version: green
  template:
    metadata:
      labels:
        app: users
        version: green
    spec:
      containers:
        - name: users
          image: ghcr.io/avtan88/enterprise/users-service:97ba310
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
