apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: enterprise-devops
spec:
  selector:
    app: search
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
